In [2]:
import numpy  as np

print(np.log(np.e)) # np.eでネイピア数e
a = np.array([1., 2., np.e**2, 10])
b = np.array([1., 2., 4., 7])

print(np.log(a)) # 配列を指定することもできる。（他の数学関数も同様)

print(np.log2(b))

c = np.array([1., 10., 20., 100])
print(np.log10(c))
print(np.log1p(a))

print(np.log(2)/np.log(4))
print(np.log(9)/np.log(3))

1.0
[0.         0.69314718 2.         2.30258509]
[0.         1.         2.         2.80735492]
[0.      1.      1.30103 2.     ]
[0.69314718 1.09861229 2.12692801 2.39789527]
0.5
2.0
