In [8]:
import numpy as np

# 3次元配列も作ることができます。
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],[[13,14,15],[16,17,18],[19,20,21],[22,23,24]]])

print(d)

print("d.shape = " + str(d.shape))

# ここには軸(axis)の考えなども混ざってきます。例えば和を求める関数はnp.sumで与えられるのですが、
np.sum(c)

# 列ごとの和を知りたい時、以下の様に軸(axis)を指定するとうまくできます。
print("np.sum(c, axis=1)" + str(np.sum(c, axis=1)))

# またこの配列の形状を変える事もできます。reshape関数を使って変えてみましょう。

print("c.reshape(3,2) = " + str(c.reshape(3,2)))
print("c.reshape(6,1) = " + str(c.reshape(6,1)))

# また転置を行うこともできます。やり方は様々ですが、配列.Tの形やtranspose関数で求めることができます。
print("c.T = " + str(c.T))
print("np.transpose(c)" + str(np.transpose(c)))

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]
d.shape = (2, 4, 3)
np.sum(c, axis=1)[ 6 15]
c.reshape(3,2) = [[1 2]
 [3 4]
 [5 6]]
c.reshape(6,1) = [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
