In [8]:
import numpy as np
# これはNumPyの代表的な特徴の１つであり、使いこなせるようになるととても便利です。

# 配列の形状にあわせて適宜配列を拡張してくれる機能となっています。何言っているのかよくわからないですよね。

# 実際のコードを見てもらったほうが早いと思うので早速みていきましょう

a = np.array([1, 2, 3])
c = np.array([[1, 2, 3], [4, 5, 6]])

print(a)
print(c)
print("a + c = " + str(a+c))
print("a * c = " + str(a*c))
# 見てわかるでしょうか。aの配列が２回繰り返されることでcへの足し算を行っていることが。 aがcの形状にあわせて拡張（この場合は行方向に要素が１回繰り返される）されたあと、通常の足し算や掛け算を行っていることになります。

# ブロードキャストについて詳しく知りたい方はこちら。

[1 2 3]
[[1 2 3]
 [4 5 6]]
a + c = [[2 4 6]
 [5 7 9]]
a * c = [[ 1  4  9]
 [ 4 10 18]]
